### ISSUE TITLE
Error Starting selenium-standalone In OpenShift/Kubernetes

### ISSUE THREAD

**Issue by calebevans** [RedHatQE/selenium-images#29]
I am receiving the following error when starting this container in OpenShift:

**Error:** 
```
Starting selenium standalone
HTTP server listening on 'localhost:8000'
"--port": couldn't convert "tcp://10.217.4.127:4444" to an integer
```

**Command used to start container:**
```
oc apply -f - <<EOF
kind: Pod
apiVersion: v1
metadata:
  name: selenium-runner
  namespace: mta
  labels:
    app: selenium
spec:
  containers:
    - resources:
        limits:
          cpu: '1'
          memory: 3Gi
        requests:
          cpu: '1'
          memory: 3Gi
      terminationMessagePath: /dev/termination-log
      name: selenium
      imagePullPolicy: Always
      volumeMounts:
        - name: shm
          mountPath: /dev/shm
      terminationMessagePolicy: File
      image: 'quay.io/redhatqe/selenium-standalone:latest'
  volumes:
    - name: shm
      emptyDir:
        medium: Memory
        sizeLimit: 2Gi
EOF
```

**Comment by calebevans** [comment]
Resolved this by overwriting the SELENIUM_PORT environment variable:

```
kind: Pod
apiVersion: v1
metadata:
  name: selenium-runner
  namespace: mta
  labels:
    app: selenium
spec:
  containers:
    - resources:
        limits:
          cpu: '1'
          memory: 3Gi
        requests:
          cpu: '1'
          memory: 3Gi
      terminationMessagePath: /dev/termination-log
      name: selenium
      imagePullPolicy: Always
      volumeMounts:
        - name: shm
          mountPath: /dev/shm
      terminationMessagePolicy: File
      image: 'quay.io/redhatqe/selenium-standalone:latest'
      env:
        - name: SELENIUM_PORT
          value: "4444"
  volumes:
    - name: shm
      emptyDir:
        medium: Memory
        sizeLimit: 2Gi
```
